FROM node:18-alpine

ENV FRONTEND_PORT ${FRONTEND_PORT}
ENV NODE_ENV=development

# Create app directory
RUN mkdir -p /usr/app/frontend
WORKDIR /usr/app/frontend

# Copying source files
COPY . /usr/app/frontend

# # Installing dependencies
RUN rm -rf node_modules
RUN npm install -g pnpm
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm fetch --frozen-lockfile
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install --frozen-lockfile



EXPOSE ${FRONTEND_PORT}

# Running the all-in-one-app
CMD ["pnpm","dev"]